export const SPREADSHEET_TOOL_NAMES = [
  'get_workbook_info',
  'get_sheets',
  'get_range_data',
  'set_range_data',
  'display_sheet',
  'create_sheet',
  'delete_sheet',
  'rename_sheet',
  'batch_rename_sheets',
  'insert_rows',
  'insert_columns',
  'delete_rows',
  'delete_columns',
  'batch_insert_rows',
] as const;
